### ISSUE TITLE
Support building with time-1.10

### ISSUE THREAD

**Issue by RyanGlScott** [phadej/time-compat#10]
`time-1.10` removes several deprecated functions that `time-compat` reexports:

```
[ 4 of 17] Compiling Data.Time.Format.Compat ( src/Data/Time/Format/Compat.hs, dist/build/Data/Time/Format/Compat.o )

src/Data/Time/Format/Compat.hs:10:5: error:
    Not in scope: ‘parseTime’
    Perhaps you meant ‘parseTimeM’ (imported from Data.Time.Format)
   |
10 |     parseTime, readTime, readsTime,
   |     ^^^^^^^^^

src/Data/Time/Format/Compat.hs:10:16: error:
    Not in scope: ‘readTime’
    Perhaps you meant one of these:
      ‘readSTime’ (imported from Data.Time.Format),
      ‘readPTime’ (imported from Data.Time.Format),
      ‘readFile’ (imported from Prelude)
   |
10 |     parseTime, readTime, readsTime,
   |                ^^^^^^^^

src/Data/Time/Format/Compat.hs:10:26: error:
    Not in scope: ‘readsTime’
    Perhaps you meant one of these:
      ‘readSTime’ (imported from Data.Time.Format),
      ‘readPTime’ (imported from Data.Time.Format)
   |
10 |     parseTime, readTime, readsTime,
   |                          ^^^^^^^^^
```

It's not clear to me whether `time-compat` should:

1. Define forward-compatible versions of these functions for newer releases of `time`,
2. Stop exporting these functions, or
3. Something else.

**Comment by phadej** [comment]
I think we should do 1 + 2, i.e both.

- make `time-compat-1.9.2.3` which would compile with `time-1.10` (important)
- and `time-compat-1.10` which would make interface as in `time-1.10` i.e. drop the re-exports (not so important, can be done later)

**Comment by phadej** [comment]
Note, we probably should have `1.9.3` adding `pastMidnight` and `sinceMidnignt`

**Comment by phadej** [comment]
Released in Released in https://hackage.haskell.org/package/time-compat-1.9.3

**Comment by phadej** [comment]
The `time-compat-1.10` can wait, I don't see any urgency to make major release
